#
# THIS CONFIGURATION IS FOR LOCAL DEVELOPMENT
#
LISTEN_PORT: 8080

# Gin
MAX_CONNECTION: 100
CONNECTION_TIMEOUT_READ: 5
CONNECTION_TIMEOUT_WRITE: 5

# Database
MAX_IDLE_CONNECTION: 10
MAX_OPEN_CONNECTION: 100