openapi: 3.1.0
info:
  title: UPSIDER Coding Test API
  description: UPSIDERのコーディングテスト用のAPI定義を記述する。
  version: 1.0.0
security:
  - ApiKeyAuth: []
externalDocs:
  description: テスト内容についてはこちらを参照
  url: https://github.com/upsidr/coding-test/blob/main/web-api-language-agnostic/README.ja.md
paths:
  /api/invoices:
    post:
      summary: 請求書データ作成
      description: |
        - 新しい請求書データを作成する
        - 請求金額 は自動的に計算されるものとする
        - 支払金額 に手数料4%を加えたものに更に手数料の消費税を加えたものを請求金額とする
        - 例) 支払金額 10,000 の場合は請求金額は 10,000 + (10,000 * 0.04 * 1.10) = 10,440
      tags:
        - invoices
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - partnerId
                - amount
                - paymentDue
              properties:
                partnerId:
                  type: string
                  description: 取引先企業ID
                amount:
                  type: integer
                  description: 支払金額
                paymentDue:
                  type: string
                  description: 支払期日（YYYYMMDD）
      responses:
        '200':
          description: 請求データ作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'
        '400':
          description: リクエストが不正
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        '401':
          description: 認証が不正
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
    get:
      summary: 請求書データ一覧取得
      description: |
        - 請求書データを取得する
        - 取得開始日と取得終了日を指定することで、その期間内の請求書データを取得する
      tags:
        - invoices
      parameters:
        - in: query
          name: startAt
          schema:
            type: string
          description: 取得開始日（YYYYMMDD）
        - in: query
          name: endAt
          schema:
            type: string
          description: 取得終了日（YYYYMMDD）
      responses:
        '200':
          description: 請求データ一覧取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoices'
        '400':
          description: リクエストが不正
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        '401':
          description: 認証が不正
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: 事前に発行されるAPIキーを指定する
  schemas:
    Invoice:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 請求書の一意の識別子
        companyId:
          type: string
          format: uuid
          description: 会社の一意の識別子
        businessPartnerId:
          type: string
          format: uuid
          description: 取引先の一意の識別子
        issueDate:
          type: string
          format: date
          description: 請求書の発行日
        paymentAmount:
          type: integer
          description: 支払金額
        fee:
          type: integer
          description: 手数料
        feeRate:
          type: number
          format: float
          description: 手数料率
        consumptionTax:
          type: integer
          description: 消費税
        taxRate:
          type: number
          format: float
          description: 消費税率
        totalAmount:
          type: integer
          description: 支払総額
        paymentDueDate:
          type: string
          format: date
          description: 支払期日
        status:
          type: string
          description: 請求書のステータス
          enum:
            - unpaid
            - processing
            - paid
            - error
    Invoices:
      type: object
      properties:
        invoices:
          type: array
          description: 請求書データ一覧
          items:
            $ref: '#/components/schemas/Invoice'
    Error400:
      type: object
      properties:
        error:
          type: string
          description: エラーメッセージ
          example: invalid request
    Error401:
      type: object
      properties:
        error:
          type: string
          description: エラーメッセージ
          example: invalid auth
    Error500:
      type: object
      properties:
        error:
          type: string
          description: エラーメッセージ
          example: internal server error
