run:
  concurrency: 4
linters:
  enable-all: true
  disable:
    - dogsled
    - godot
    - goheader
    - gomodguard
    - musttag
    - forbidigo
    - exhaustruct
    - wsl
    - gomoddirectives
    - depguard
    - funlen
    - varnamelen
    - gci
    - nlreturn
    - wrapcheck
    - err113
    - dupl
    - gofumpt
    - lll
    - exportloopref
linters-settings:
  cyclop:
    max-complexity: 30
output:
  formats:
    - format: colored-line-number