openapi: 3.1.0
info:
  title: UPSIDER Coding Test API
  description: UPSIDERのコーディングテスト用のAPI定義を記述する。
  version: 1.0.0
externalDocs:
  description: 'テスト内容についてはこちらを参照'
  url: 'https://github.com/upsidr/coding-test/blob/main/web-api-language-agnostic/README.ja.md'
security:
  - ApiKeyAuth: []
paths:
  /api/invoices:
    $ref: "./paths/invoices.yaml#/invoices"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: 事前に発行されるAPIキーを指定する
