name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
      - staging
      - develop
      - feature/*
      - hotfix/*

jobs:
  lint-cmd:
    name: lint cmd
    runs-on: ubuntu-latest-4
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false
      - name: Lint cmd/api
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: "--config=../../../configs/.golangci.yaml --timeout=3m"
          working-directory: cmd/api

  test-cmd:
    name: test cmd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false
      - name: test cmd
        run: go test -v -cover ./cmd/...

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Dockerfile in payment service
        uses: hadolint/hadolint-action@master
        with:
          config: ./configs/.hadolint.yaml
          dockerfile: "Dockerfile"
          recursive: true
          verbose: true